version: "3.3"
services:
    dwp2-api:
        container_name: dwp2api
        build: .
        image: dwp2api
        depends_on:
            - dwp2-db
        volumes:
            - .:/var/www/html
            - /var/www/html/vendor
    dwp2-web:
        container_name: dwp2web
        build: ./docker-services/nginx
        image: dwpweb
        ports:
            - "8090:80"
        depends_on:
            - dwp2-api
        volumes:
            - .:/var/www/html
    dwp2-db:
        container_name: dwp2db
        build: ./docker-services/mysql
        image: dwp2db
        ports:
            - "33064:3306"
        environment:
            MYSQL_DATABASE: "dwp2"
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "dwp2"
            MYSQL_PASSWORD: "dwp2"
        volumes:
            - dwp2-db:/var/lib/mysql
volumes:
    dwp2-db:
        external: true
